In [3]:
%load_ext autoreload
%autoreload 2
from sklearn import datasets
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
from continuum_gaussian_bandits import ContinuumArmedBandit

In [5]:
X,y = datasets.make_regression(n_samples=500,n_features=32)

In [6]:
idxs = np.random.choice(500,25)
X_train = X[idxs]
y_train = y[idxs]

In [7]:
cab = ContinuumArmedBandit(X_train, y_train)

Test Calculations

In [8]:
K = cab.gpr.K
noise_var = cab.gpr.noise_var
N = cab.N
a = (K + noise_var * np.eye(N)).dot(y_train)

In [9]:
cab.gpr.kernel_.get_params

<bound method KernelOperator.get_params of RBF(length_scale=[0.891, 0.828, 0.963, 0.899, 0.869, 1.14, 0.918, 0.919, 1.02, 0.948, 0.943, 0.808, 0.856, 0.983, 0.872, 1.08, 0.849, 1.08, 1.04, 1.03, 1.18, 1.1, 0.998, 0.863, 0.886, 1.01, 1.03, 0.904, 0.889, 0.885, 0.983, 1.08]) + WhiteKernel(noise_level=3.33e+04)>

In [10]:
cab.select_action()

array([ 2409.69958734, -1271.77912694,  -165.78419949,  -698.34555632,
         840.70808286, -1177.13788567,   293.5653496 ,   361.8193729 ,
        -370.73866674,   782.64659419,   -69.16947561,  -573.19520361,
         849.33825998,   976.21368472,  -243.68381392,   558.23003724,
       -1005.47160274,   749.50062448, -1040.96989933, -1114.10402771,
         811.22902488, -1084.98626029,  1076.04725462,  1534.42841523,
       -1643.06666926, -1721.6205443 ,   951.13187557,   462.4776406 ,
       -1766.79162434,   935.54053407,  1301.03606645,  1823.13202634])

In [11]:
idx = np.random.choice(500)
x = X[idx]

In [12]:
m = cab.get_merit(x,X_train)
print(m)

1.0


In [13]:
x2 = cab.select_action()
print(x2)

[ 2409.69958734 -1271.77912694  -165.78419949  -698.34555632   840.70808286
 -1177.13788567   293.5653496    361.8193729   -370.73866674   782.64659419
   -69.16947561  -573.19520361   849.33825998   976.21368472  -243.68381392
   558.23003724 -1005.47160274   749.50062448 -1040.96989933 -1114.10402771
   811.22902488 -1084.98626029  1076.04725462  1534.42841523 -1643.06666926
 -1721.6205443    951.13187557   462.4776406  -1766.79162434   935.54053407
  1301.03606645  1823.13202634]


In [14]:
cab.get_derivative_mean(x, X_train)

array([  1.79164113e-15,   1.93492042e-15,  -1.66107935e-15,
        -7.95261824e-17,  -2.70420520e-15,   3.87635705e-17,
         1.21619915e-15,   2.03270478e-15,  -2.51679242e-16,
        -1.11794407e-15,  -8.29071859e-16,  -3.08596577e-15,
        -9.69728012e-16,  -3.19840190e-16,   4.89580955e-16,
        -3.87310843e-16,   1.93991672e-15,   6.88460753e-16,
         1.09993113e-15,  -4.81627162e-16,   1.53324598e-15,
         1.06470874e-15,   3.04093921e-15,  -1.07440433e-15,
         1.48919272e-15,  -3.27600627e-15,  -4.88688011e-16,
        -6.39533185e-17,  -3.13068236e-15,  -5.32234440e-15,
        -1.27021415e-15,  -1.44727239e-17])

In [15]:
cab.get_derivative_std(x, X_train)

array([ -7.26117858e-17,  -6.24820205e-17,   1.99306295e-17,
         3.06367958e-17,   8.69855984e-17,  -7.34034455e-19,
         1.00949853e-17,  -6.43731884e-17,   3.98459937e-17,
         3.00973020e-17,   7.60253099e-17,   9.10261722e-17,
         5.39047702e-17,   3.13362006e-17,  -4.58488331e-17,
         8.79715662e-18,  -6.63881931e-17,  -1.62806948e-17,
        -6.56146500e-17,   3.05342032e-17,  -3.84117529e-17,
        -4.11564430e-17,  -1.09546210e-16,   8.50485005e-18,
        -9.03937483e-17,   9.18524077e-17,   4.05720104e-17,
        -1.81697209e-17,   1.14160885e-16,   1.85935601e-16,
         6.60591782e-17,   1.59617732e-17])