In [16]:
%load_ext autoreload
%autoreload 2
from sklearn import datasets
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
from continuum_gaussian_bandits import ContinuumArmedBandit

In [18]:
X,y = datasets.make_regression(n_samples=500,n_features=32)

In [19]:
idxs = np.random.choice(500,25)
X_train = X[idxs]
y_train = y[idxs]

In [20]:
cab = ContinuumArmedBandit(X_train, y_train)

Test Calculations

In [21]:
K = cab.gpr.K
noise_var = cab.gpr.noise_var
N = cab.N
a = (K + noise_var * np.eye(N)).dot(y_train)

In [22]:
cab.gpr.kernel_.get_params

<bound method KernelOperator.get_params of RBF(length_scale=[1.17, 1.05, 1.1, 0.758, 0.909, 0.944, 1.01, 1.05, 1.02, 0.875, 1.1, 0.88, 0.931, 0.954, 1.13, 0.924, 0.955, 0.941, 1.02, 1.06, 1.11, 1.04, 0.915, 0.984, 1.21, 1.03, 0.944, 1, 0.886, 1.16, 1.08, 0.996]) + WhiteKernel(noise_level=2.95e+04)>

In [23]:
cab.select_action()

array([  653.11409607,  2266.31880298,  1311.21823455,  -574.21421901,
        -610.48463709,   -98.99112212,   730.95131786,   184.45481352,
        -797.25877418,  1454.74222426,  -234.54189994,   374.28205798,
        1052.13411186,  -521.29382021,  2990.61292682,   296.7869975 ,
        1000.10690037,   306.41426729,   -18.18452429,   821.93882939,
         746.7112182 ,  1315.52789885,   -94.61760364,   486.96227046,
        -829.14427244,  -181.64157346, -1539.00433047,  2033.42030298,
        -664.86706606,    41.92061229,   361.73306354, -2457.76603464])

In [24]:
idx = np.random.choice(500)
x = X[idx]

In [25]:
m = cab.get_merit(x,X_train)
print(m)

1.0


In [26]:
x2 = cab.select_action()
print(x2)

[  653.11409607  2266.31880298  1311.21823455  -574.21421901  -610.48463709
   -98.99112212   730.95131786   184.45481352  -797.25877418  1454.74222426
  -234.54189994   374.28205798  1052.13411186  -521.29382021  2990.61292682
   296.7869975   1000.10690037   306.41426729   -18.18452429   821.93882939
   746.7112182   1315.52789885   -94.61760364   486.96227046  -829.14427244
  -181.64157346 -1539.00433047  2033.42030298  -664.86706606    41.92061229
   361.73306354 -2457.76603464]


In [27]:
cab.get_derivative_mean(x, X_train)

array([ -3.43915971e-12,   3.84432772e-12,  -2.12942954e-12,
        -1.59140558e-12,   3.68514688e-12,   2.39740223e-12,
        -5.37993199e-12,   9.99939058e-14,   1.54286521e-12,
        -4.14838161e-12,  -2.55858062e-12,  -2.10932496e-12,
        -2.30973539e-12,   4.12893623e-12,  -1.93863058e-13,
        -6.53835960e-12,   2.74049089e-13,  -4.63285911e-12,
        -1.57473937e-12,   2.58365330e-12,  -3.11619074e-13,
        -5.03351382e-12,   3.16169748e-12,  -2.53206394e-12,
         1.51892947e-12,  -2.74256841e-13,   1.51587808e-12,
         2.06565824e-12,   1.50882663e-12,  -2.19243824e-13,
        -2.64838128e-12,  -1.90348450e-12])

In [28]:
cab.get_derivative_std(x, X_train)

array([ -1.50398457e-14,   8.78762401e-14,  -9.84777796e-14,
        -4.27963359e-13,   2.25841984e-13,  -2.64342075e-13,
        -1.11548979e-13,   1.24274006e-13,   2.36573367e-13,
        -7.07877711e-14,   3.44297670e-13,  -1.44753905e-13,
        -2.22370352e-13,  -1.67957004e-13,  -6.66078734e-14,
        -3.39378214e-13,   3.54471166e-13,   1.73416141e-13,
        -2.79964690e-13,  -6.76619910e-14,   2.11057816e-13,
         4.59075797e-14,   3.77263167e-13,   2.80860132e-13,
        -1.50691369e-13,   7.65208894e-14,  -1.75596176e-13,
        -1.58175536e-13,   4.49138439e-13,   1.50783049e-14,
        -2.60112076e-13,  -2.04156750e-14])

In [29]:
cab.get_s(x, X_train)

array([ -3.45419956e-12,   3.93220396e-12,  -2.22790732e-12,
        -2.01936894e-12,   3.91098886e-12,   2.13306016e-12,
        -5.49148097e-12,   2.24267911e-13,   1.77943857e-12,
        -4.21916938e-12,  -2.21428295e-12,  -2.25407887e-12,
        -2.53210574e-12,   3.96097922e-12,  -2.60470932e-13,
        -6.87773781e-12,   6.28520255e-13,  -4.45944296e-12,
        -1.85470406e-12,   2.51599131e-12,  -1.00561258e-13,
        -4.98760624e-12,   3.53896065e-12,  -2.25120380e-12,
         1.36823810e-12,  -1.97735951e-13,   1.34028191e-12,
         1.90748271e-12,   1.95796506e-12,  -2.04165519e-13,
        -2.90849335e-12,  -1.92390018e-12])

In [30]:
cab.get_q_mean(x, X_train)

1.7860453451743732e-06